from typing import Protocol, Sequence
from .models import Diagnosis, RepairCandidate, ValidationReport, ViolationCase


class Diagnoser(Protocol):
    def diagnose(self, case: ViolationCase) -> Diagnosis: ...


class RepairPlanner(Protocol):
    def propose(self, case: ViolationCase, diagnosis: Diagnosis) -> Sequence[RepairCandidate]: ...


class DRCTool(Protocol):
    def inspect(self, case: ViolationCase) -> ValidationReport: ...
    def snapshot(self) -> object: ...
    def apply(self, repair: RepairCandidate) -> None: ...
    def validate(self, case: ViolationCase) -> ValidationReport: ...
    def commit(self, snapshot: object) -> None: ...
    def rollback(self, snapshot: object) -> None: ...


class EpisodeStore(Protocol):
    def record(self, episode: dict[str, object]) -> None: ...
